# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0002_question_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('single', 'Single choice'), ('multi', 'Multi choice')], max_length=10),
        ),
    ]
