# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0010_auto_20171109_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
