# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0011_question_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
