# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0012_auto_20171109_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
