# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0015_auto_20171109_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='This field is the question that will be shown', max_length=500),
        ),
    ]
