# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0016_auto_20171109_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[(None, 'Choose a type for answers!'), ('Answer Type', [('single', 'Single choice'), ('multi', 'Multi choice')])], max_length=10),
        ),
    ]
