# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synerg_lab', '0018_auto_20171122_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='This will be shown as question for feedback', max_length=500),
        ),
    ]
